DELIMITER $$
CREATE PROCEDURE CDisplay()
BEGIN
	DECLARE CUST_NAME VARCHAR(255) DEFAULT ``;
    DECLARE CUST_CITY VARCHAR(255) DEFAULT ``;
    DECLARE CUST_COUNTRY VARCHAR(255) DEFAULT ``;
	DECLARE GRADE INT DEFAULT 0;
    DECLARE demo CURSOR
    SELECT CUST_NAME, CUST_CITY, CUST_COUNTRY, GRADE FROM customer
    WHERE AGENT_CODE=`A00`;
    
    OPEN ccdisplay;
    FETCH NEXT FROM demo INTO @CUST_NAME, CUST_CITY, CUST_COUNTRY, GRADE;
    
    WHILE @@FETCH_STATUS = 0 
    BEGIN
		PRINT @product_name + CAST(AGENT_CODE AS varchar); 
        FETCH NEXT FROM demo INTO CUST_NAME, CUST_CITY, CUST_COUNTRY, GRADE; 
	END;
    CLOSE demo; 
    DEALLOCATE demo;
END$$
DELIMITER ;

CALL CDisplay();