use COMPANY;

SELECT DEPARTMENT.Mgr_ssn, DEPARTMENT.Dnumber FROM DEPARTMENT, EMPLOYEE, WORKS_ON, DEPENDENT WHERE DEPARTMENT.Dnumber=EMPLOYEE.Dno AND EMPLOYEE.Ssn=WORKS_ON.Essn AND WORKS_ON.Essn=DEPENDENT.Essn;